sudo: false
language: node_js
node_js:
  - node
  - '6'
addons:
  code_climate:
    repo_token: 498707228e4260677935eadfa95a35c24a9c2e9877bf05200d9c3aafb520abf6
before_script:
  - 'npm install -g codeclimate-test-reporter'
after_script:
  - 'codeclimate-test-reporter < coverage/lcov.info'
notifications:
  email: false
  slack:
    rooms:
      secure: Y7GyAUEjnjzyazj3zo3PXcl9Z1TN7SGjfUGQacJ+U/pCKfZKzgUhezZ5hTMz71bxL6/+2TuvKHQM3NQgrgR5JhdsPlrJfIW9FK2rNNPBN9p/DWZGv2bjEKPCcstdkuF/1NCru8up9092pZ3Fa8n6bjXicswCMVKjAmYrXqsWEMU=
