version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
  - package_manager: "javascript"
    directory: "/packages/adapter-commons"
    update_schedule: "weekly"
  - package_manager: "javascript"
    directory: "/packages/adapter-tests"
    update_schedule: "weekly" 
  - package_manager: "javascript"
    directory: "/packages/authentication"
    update_schedule: "weekly"
  - package_manager: "javascript"
    directory: "/packages/authentication-client"
    update_schedule: "weekly"
  - package_manager: "javascript"
    directory: "/packages/authentication-local"
    update_schedule: "weekly"
  - package_manager: "javascript"
    directory: "/packages/authentication-oauth"
    update_schedule: "weekly"
  - package_manager: "javascript"
    directory: "/packages/client"
    update_schedule: "weekly"
  - package_manager: "javascript"
    directory: "/packages/commons"
    update_schedule: "weekly"
  - package_manager: "javascript"
    directory: "/packages/configuration"
    update_schedule: "weekly"
  - package_manager: "javascript"
    directory: "/packages/errors"
    update_schedule: "weekly"
  - package_manager: "javascript"
    directory: "/packages/express"
    update_schedule: "weekly"
  - package_manager: "javascript"
    directory: "/packages/feathers"
    update_schedule: "weekly"
  - package_manager: "javascript"
    directory: "/packages/primus"
    update_schedule: "weekly"
  - package_manager: "javascript"
    directory: "/packages/primus-client"
    update_schedule: "weekly"
  - package_manager: "javascript"
    directory: "/packages/rest-client"
    update_schedule: "weekly"
  - package_manager: "javascript"
    directory: "/packages/socketio"
    update_schedule: "weekly"
  - package_manager: "javascript"
    directory: "/packages/socketio-client"
    update_schedule: "weekly"
  - package_manager: "javascript"
    directory: "/packages/tests"
    update_schedule: "weekly"
  - package_manager: "javascript"
    directory: "/packages/transport-commons"
    update_schedule: "weekly"
